from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(728, 424)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(0, 20, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 57))
        self.frame_superior.setStyleSheet("QFrame{\n"
"background-color:rgb(0, 20, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(0, 155, 255);\n"
"border-radius:20px;\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_menu = QtWidgets.QPushButton(self.frame_superior)
        self.btn_menu.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_menu.setStyleSheet("")
        self.btn_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/menus/barra-de-menus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu.setIcon(icon)
        self.btn_menu.setIconSize(QtCore.QSize(38, 38))
        self.btn_menu.setObjectName("btn_menu")
        self.horizontalLayout_2.addWidget(self.btn_menu)
        spacerItem = QtWidgets.QSpacerItem(267, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.btn_restaurar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_restaurar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_restaurar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/menus/restaurar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_restaurar.setIcon(icon1)
        self.btn_restaurar.setIconSize(QtCore.QSize(38, 38))
        self.btn_restaurar.setObjectName("btn_restaurar")
        self.horizontalLayout_2.addWidget(self.btn_restaurar)
        self.btn_minimizar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_minimizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/menus/minimizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimizar.setIcon(icon2)
        self.btn_minimizar.setIconSize(QtCore.QSize(38, 38))
        self.btn_minimizar.setObjectName("btn_minimizar")
        self.horizontalLayout_2.addWidget(self.btn_minimizar)
        self.btn_maximizar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_maximizar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Downloads/menus/maximizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximizar.setIcon(icon3)
        self.btn_maximizar.setIconSize(QtCore.QSize(38, 38))
        self.btn_maximizar.setObjectName("btn_maximizar")
        self.horizontalLayout_2.addWidget(self.btn_maximizar)
        self.btn_cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.btn_cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_cerrar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../Downloads/menus/cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cerrar.setIcon(icon4)
        self.btn_cerrar.setIconSize(QtCore.QSize(38, 38))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout_2.addWidget(self.btn_cerrar)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_contenido = QtWidgets.QFrame(self.frame)
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contenido.setObjectName("frame_contenido")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_contenido)
        self.horizontalLayout_3.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_control = QtWidgets.QFrame(self.frame_contenido)
        self.frame_control.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_control.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_control.setStyleSheet("QFrame{\n"
"background-color:rgb(0, 0, 120);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:rgb(0, 20, 255);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"font:77 11pt\"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color :rgb(0, 155, 255);\n"
"border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"color:rgb(0. 0, 0);\n"
"font:77 12pt\"Arial Black\";\n"
"}")
        self.frame_control.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_control.setObjectName("frame_control")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_control)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_base_datos = QtWidgets.QPushButton(self.frame_control)
        self.btn_base_datos.setMinimumSize(QtCore.QSize(0, 40))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../Downloads/menus/base-de-datos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_base_datos.setIcon(icon5)
        self.btn_base_datos.setIconSize(QtCore.QSize(38, 38))
        self.btn_base_datos.setObjectName("btn_base_datos")
        self.verticalLayout_3.addWidget(self.btn_base_datos)
        self.btn_nuevo_registro = QtWidgets.QPushButton(self.frame_control)
        self.btn_nuevo_registro.setMinimumSize(QtCore.QSize(0, 40))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../Downloads/menus/archivo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_nuevo_registro.setIcon(icon6)
        self.btn_nuevo_registro.setIconSize(QtCore.QSize(38, 38))
        self.btn_nuevo_registro.setObjectName("btn_nuevo_registro")
        self.verticalLayout_3.addWidget(self.btn_nuevo_registro)
        self.btn_actualizar_reg = QtWidgets.QPushButton(self.frame_control)
        self.btn_actualizar_reg.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_actualizar_reg.setIcon(icon5)
        self.btn_actualizar_reg.setIconSize(QtCore.QSize(38, 38))
        self.btn_actualizar_reg.setObjectName("btn_actualizar_reg")
        self.verticalLayout_3.addWidget(self.btn_actualizar_reg)
        self.btn_eliminar_reg = QtWidgets.QPushButton(self.frame_control)
        self.btn_eliminar_reg.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_eliminar_reg.setIcon(icon5)
        self.btn_eliminar_reg.setIconSize(QtCore.QSize(38, 38))
        self.btn_eliminar_reg.setObjectName("btn_eliminar_reg")
        self.verticalLayout_3.addWidget(self.btn_eliminar_reg)
        self.horizontalLayout_3.addWidget(self.frame_control)
        self.frame_paginas = QtWidgets.QFrame(self.frame_contenido)
        self.frame_paginas.setStyleSheet("QFrame{\n"
"background-color:rgb(0,20,255)\n"
"}\n"
"\n"
"QLabel{\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color:rgb(0,20,255);\n"
"color:rgb(0, 0, 0);\n"
"border:0px solid rgb(0, 20, 255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"border:0px;\n"
"background-color:rgb(0, 155, 255);\n"
"color:rgb(0, 0, 0);\n"
"border-bottom:2px solid rgb(0, 20, 255);\n"
"font: 87 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:rgb(0,20,255);\n"
"border-radius:15px;\n"
"color:rgb(0, 0, 0);\n"
"font: 77 11pt \"Arial Black\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(0 ,155, 255);\n"
"border-radius:15px;\n"
"color:rgb(0, 0, 0);\n"
"font: 77 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QTableWidget{\n"
"background-color:rgb(200, 200, 200);\n"
"color:rgb(0, 0, 120);\n"
"gridline-color:rgb(0, 0, 120);\n"
"font-size:12pt;\n"
"color:rgb(0, 0, 0);\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"background-color:rgb(200, 200, 200);\n"
"border:1px solid rgb(0, 0, 0);\n"
"font-size: 12pt;\n"
"}\n"
"\n"
"QTableWidgetQtableCornerButton{\n"
"background-color:rgb(0, 20, 255);\n"
"border:1px solid rgb(0, 0, 0);\n"
"}\n"
"")
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_paginas)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_paginas)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_datos = QtWidgets.QWidget()
        self.page_datos.setObjectName("page_datos")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_datos)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.page_datos)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.tabla_productos = QtWidgets.QTableWidget(self.page_datos)
        self.tabla_productos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabla_productos.setAutoScroll(True)
        self.tabla_productos.setObjectName("tabla_productos")
        self.tabla_productos.setColumnCount(5)
        self.tabla_productos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(4, item)
        self.tabla_productos.horizontalHeader().setDefaultSectionSize(96)
        self.verticalLayout_4.addWidget(self.tabla_productos)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btn_refrescar = QtWidgets.QPushButton(self.page_datos)
        self.btn_refrescar.setEnabled(True)
        self.btn_refrescar.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_refrescar.setObjectName("btn_refrescar")
        self.horizontalLayout_4.addWidget(self.btn_refrescar)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.stackedWidget.addWidget(self.page_datos)
        self.page_registrar = QtWidgets.QWidget()
        self.page_registrar.setObjectName("page_registrar")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_registrar)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.page_registrar)
        self.label_7.setEnabled(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.reg_cantidad = QtWidgets.QLineEdit(self.page_registrar)
        self.reg_cantidad.setText("")
        self.reg_cantidad.setObjectName("reg_cantidad")
        self.gridLayout.addWidget(self.reg_cantidad, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_registrar)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page_registrar)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page_registrar)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page_registrar)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.reg_nombre = QtWidgets.QLineEdit(self.page_registrar)
        self.reg_nombre.setText("")
        self.reg_nombre.setObjectName("reg_nombre")
        self.gridLayout.addWidget(self.reg_nombre, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 1)
        self.reg_modelo = QtWidgets.QLineEdit(self.page_registrar)
        self.reg_modelo.setText("")
        self.reg_modelo.setObjectName("reg_modelo")
        self.gridLayout.addWidget(self.reg_modelo, 2, 1, 1, 1)
        self.reg_codigo = QtWidgets.QLineEdit(self.page_registrar)
        self.reg_codigo.setText("")
        self.reg_codigo.setObjectName("reg_codigo")
        self.gridLayout.addWidget(self.reg_codigo, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page_registrar)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.reg_precio = QtWidgets.QLineEdit(self.page_registrar)
        self.reg_precio.setText("")
        self.reg_precio.setObjectName("reg_precio")
        self.gridLayout.addWidget(self.reg_precio, 3, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.signal_registrar = QtWidgets.QLabel(self.page_registrar)
        self.signal_registrar.setMinimumSize(QtCore.QSize(200, 30))
        self.signal_registrar.setText("")
        self.signal_registrar.setAlignment(QtCore.Qt.AlignCenter)
        self.signal_registrar.setObjectName("signal_registrar")
        self.horizontalLayout_6.addWidget(self.signal_registrar)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.btn_registrar = QtWidgets.QPushButton(self.page_registrar)
        self.btn_registrar.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_registrar.setObjectName("btn_registrar")
        self.horizontalLayout_6.addWidget(self.btn_registrar)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.stackedWidget.addWidget(self.page_registrar)
        self.page_actualizar = QtWidgets.QWidget()
        self.page_actualizar.setObjectName("page_actualizar")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_actualizar)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.page_actualizar)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.page_actualizar)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.line_actualizar_buscar = QtWidgets.QLineEdit(self.page_actualizar)
        self.line_actualizar_buscar.setObjectName("line_actualizar_buscar")
        self.horizontalLayout_9.addWidget(self.line_actualizar_buscar)
        self.btn_buscar_actualizar = QtWidgets.QPushButton(self.page_actualizar)
        self.btn_buscar_actualizar.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_buscar_actualizar.setObjectName("btn_buscar_actualizar")
        self.horizontalLayout_9.addWidget(self.btn_buscar_actualizar)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.act_cantidad = QtWidgets.QLineEdit(self.page_actualizar)
        self.act_cantidad.setText("")
        self.act_cantidad.setObjectName("act_cantidad")
        self.gridLayout_2.addWidget(self.act_cantidad, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.page_actualizar)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.page_actualizar)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.page_actualizar)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.page_actualizar)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 0, 1, 1)
        self.act_nombre = QtWidgets.QLineEdit(self.page_actualizar)
        self.act_nombre.setText("")
        self.act_nombre.setObjectName("act_nombre")
        self.gridLayout_2.addWidget(self.act_nombre, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 2, 2, 1, 1)
        self.act_modelo = QtWidgets.QLineEdit(self.page_actualizar)
        self.act_modelo.setText("")
        self.act_modelo.setObjectName("act_modelo")
        self.gridLayout_2.addWidget(self.act_modelo, 2, 1, 1, 1)
        self.act_codigo = QtWidgets.QLineEdit(self.page_actualizar)
        self.act_codigo.setText("")
        self.act_codigo.setObjectName("act_codigo")
        self.gridLayout_2.addWidget(self.act_codigo, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.page_actualizar)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 4, 0, 1, 1)
        self.act_precio = QtWidgets.QLineEdit(self.page_actualizar)
        self.act_precio.setText("")
        self.act_precio.setObjectName("act_precio")
        self.gridLayout_2.addWidget(self.act_precio, 3, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.signal_actualizar = QtWidgets.QLabel(self.page_actualizar)
        self.signal_actualizar.setMinimumSize(QtCore.QSize(200, 30))
        self.signal_actualizar.setText("")
        self.signal_actualizar.setAlignment(QtCore.Qt.AlignCenter)
        self.signal_actualizar.setObjectName("signal_actualizar")
        self.horizontalLayout_8.addWidget(self.signal_actualizar)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.btn_actualizar = QtWidgets.QPushButton(self.page_actualizar)
        self.btn_actualizar.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_actualizar.setObjectName("btn_actualizar")
        self.horizontalLayout_8.addWidget(self.btn_actualizar)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.stackedWidget.addWidget(self.page_actualizar)
        self.page_eliminar = QtWidgets.QWidget()
        self.page_eliminar.setObjectName("page_eliminar")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_eliminar)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_19 = QtWidgets.QLabel(self.page_eliminar)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_7.addWidget(self.label_19)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_18 = QtWidgets.QLabel(self.page_eliminar)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_11.addWidget(self.label_18)
        self.line_eliminar_buscar = QtWidgets.QLineEdit(self.page_eliminar)
        self.line_eliminar_buscar.setObjectName("line_eliminar_buscar")
        self.horizontalLayout_11.addWidget(self.line_eliminar_buscar)
        self.btn_buscar_borrar = QtWidgets.QPushButton(self.page_eliminar)
        self.btn_buscar_borrar.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_buscar_borrar.setObjectName("btn_buscar_borrar")
        self.horizontalLayout_11.addWidget(self.btn_buscar_borrar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.tabla_borrar = QtWidgets.QTableWidget(self.page_eliminar)
        self.tabla_borrar.setObjectName("tabla_borrar")
        self.tabla_borrar.setColumnCount(5)
        self.tabla_borrar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_borrar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_borrar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_borrar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_borrar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_borrar.setHorizontalHeaderItem(4, item)
        self.tabla_borrar.horizontalHeader().setDefaultSectionSize(96)
        self.verticalLayout_7.addWidget(self.tabla_borrar)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.signal_eliminar = QtWidgets.QLabel(self.page_eliminar)
        self.signal_eliminar.setMinimumSize(QtCore.QSize(200, 30))
        self.signal_eliminar.setText("")
        self.signal_eliminar.setAlignment(QtCore.Qt.AlignCenter)
        self.signal_eliminar.setObjectName("signal_eliminar")
        self.horizontalLayout_10.addWidget(self.signal_eliminar)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.btn_eliminar = QtWidgets.QPushButton(self.page_eliminar)
        self.btn_eliminar.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.horizontalLayout_10.addWidget(self.btn_eliminar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.stackedWidget.addWidget(self.page_eliminar)
        self.horizontalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_3.addWidget(self.frame_paginas)
        self.verticalLayout_2.addWidget(self.frame_contenido)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_base_datos.setText(_translate("MainWindow", "BASE DATOS"))
        self.btn_nuevo_registro.setText(_translate("MainWindow", "REGISTRAR"))
        self.btn_actualizar_reg.setText(_translate("MainWindow", "ACTUALIZAR"))
        self.btn_eliminar_reg.setText(_translate("MainWindow", "ELIMINAR"))
        self.label.setText(_translate("MainWindow", "PRODUCTOS"))
        item = self.tabla_productos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CODIGO"))
        item = self.tabla_productos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tabla_productos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "MODELO"))
        item = self.tabla_productos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PRECIO"))
        item = self.tabla_productos.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CANTIDAD"))
        self.btn_refrescar.setText(_translate("MainWindow", "REFRESCAR"))
        self.label_7.setText(_translate("MainWindow", "REGISTRAR PRODUCTOS"))
        self.label_2.setText(_translate("MainWindow", "CODIGO"))
        self.label_3.setText(_translate("MainWindow", "NOMBRE"))
        self.label_4.setText(_translate("MainWindow", "MODELO"))
        self.label_5.setText(_translate("MainWindow", "PRECIO"))
        self.label_6.setText(_translate("MainWindow", "CANTIDAD"))
        self.btn_registrar.setText(_translate("MainWindow", "REGISTRAR"))
        self.label_9.setText(_translate("MainWindow", "ACTUALIZAR PRODUCTO"))
        self.label_10.setText(_translate("MainWindow", "NOMBRE  PRODUCTO:"))
        self.btn_buscar_actualizar.setText(_translate("MainWindow", "BUSCAR"))
        self.label_11.setText(_translate("MainWindow", "CODIGO"))
        self.label_12.setText(_translate("MainWindow", "NOMBRE"))
        self.label_13.setText(_translate("MainWindow", "MODELO"))
        self.label_14.setText(_translate("MainWindow", "PRECIO"))
        self.label_15.setText(_translate("MainWindow", "CANTIDAD"))
        self.btn_actualizar.setText(_translate("MainWindow", "ACTUALIZAR"))
        self.label_19.setText(_translate("MainWindow", "ELIMINAR PRODUCTOS"))
        self.label_18.setText(_translate("MainWindow", "NOMBRE  PRODUCTO:"))
        self.btn_buscar_borrar.setText(_translate("MainWindow", "BUSCAR"))
        item = self.tabla_borrar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CODIGO"))
        item = self.tabla_borrar.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tabla_borrar.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "MODELO"))
        item = self.tabla_borrar.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PRECIO"))
        item = self.tabla_borrar.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CANTIDAD"))
        self.btn_eliminar.setText(_translate("MainWindow", "ELIMINAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
