
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 550)
        MainWindow.setMinimumSize(QtCore.QSize(400, 550))
        MainWindow.setMaximumSize(QtCore.QSize(400, 550))
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(170, 0, 255, 255), stop:1 rgba(100, 100, 100, 255));}\n"
"    \n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 340, 460))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 306, 386))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 12, 0, 1, 1)
        self.line_contra = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_contra.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(226, 226, 226);")
        self.line_contra.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_contra.setObjectName("line_contra")
        self.gridLayout.addWidget(self.line_contra, 8, 2, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 11, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 2)
        self.line_correo = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_correo.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(226, 226, 226);")
        self.line_correo.setObjectName("line_correo")
        self.gridLayout.addWidget(self.line_correo, 7, 2, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 10, 0, 1, 4)
        self.line_edad = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_edad.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(226, 226, 226);")
        self.line_edad.setObjectName("line_edad")
        self.gridLayout.addWidget(self.line_edad, 3, 2, 1, 2)
        self.btn_regresar = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_regresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_regresar.setStyleSheet("border-radius:6px;\n"
"background-color: rgb(255, 48, 48);")
        self.btn_regresar.setObjectName("btn_regresar")
        self.gridLayout.addWidget(self.btn_regresar, 12, 1, 1, 2)
        self.line_nombre = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_nombre.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(226, 226, 226);")
        self.line_nombre.setObjectName("line_nombre")
        self.gridLayout.addWidget(self.line_nombre, 0, 2, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 11, 3, 1, 1)
        self.line_ap = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_ap.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(226, 226, 226);")
        self.line_ap.setObjectName("line_ap")
        self.gridLayout.addWidget(self.line_ap, 1, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.line_cel = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_cel.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(226, 226, 226);")
        self.line_cel.setObjectName("line_cel")
        self.gridLayout.addWidget(self.line_cel, 6, 2, 1, 2)
        self.line_am = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_am.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(226, 226, 226);")
        self.line_am.setObjectName("line_am")
        self.gridLayout.addWidget(self.line_am, 2, 2, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.btn_registrar = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_registrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_registrar.setStyleSheet("border-radius:6px;\n"
"background-color: rgb(170, 170, 255);\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"background-color: rgb(132, 66, 198);\n"
"\n"
"}")
        self.btn_registrar.setObjectName("btn_registrar")
        self.gridLayout.addWidget(self.btn_registrar, 11, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 0, 1, 2)
        self.line_contra_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_contra_2.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(226, 226, 226);")
        self.line_contra_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_contra_2.setObjectName("line_contra_2")
        self.gridLayout.addWidget(self.line_contra_2, 9, 2, 1, 2)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setEditable(False)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 5, 1, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 12, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Forma de registro"))
        self.label_6.setText(_translate("MainWindow", "Celular:"))
        self.label_4.setText(_translate("MainWindow", "Edad:"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Sexo:</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Contraseña:"))
        self.btn_regresar.setText(_translate("MainWindow", "Regresar"))
        self.label_3.setText(_translate("MainWindow", "Apellido Materno:"))
        self.label_2.setText(_translate("MainWindow", "Apellido Paterno:"))
        self.label.setText(_translate("MainWindow", "Nombre(s):"))
        self.btn_registrar.setText(_translate("MainWindow", "Registrar"))
        self.label_9.setText(_translate("MainWindow", "Confirmar contraseña:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Hombre"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Mujer"))
        self.label_7.setText(_translate("MainWindow", "Correo:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
